/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bms.view;

import bms.controller.AccountController;
import bms.model.Account;
import java.sql.SQLException;
import java.util.Random;
import javax.swing.JOptionPane;
/**
 *
 * @author acer
 */
public class SignUpThirdForm extends javax.swing.JFrame {
    private long random;
    private String nic;
    private String account;
    private String services;
    private String cardNumber;
    private int pinNumber;
    private Random card = new Random();
   
    /**
     * Creates new form SignUpForm
     */
    public SignUpThirdForm(long random,String nic) {
        this.nic = nic;
        this.random = random;
        long cardPrefix = 5040930000000000L; 
        long cardSuffix = Math.abs(card.nextLong() % 1000000L); 
        cardNumber = String.format("%016d", cardPrefix + cardSuffix);
        pinNumber = card.nextInt(9000) + 1000; 
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblRandom = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        radioSaving = new javax.swing.JRadioButton();
        radioCurrent = new javax.swing.JRadioButton();
        radioFixed = new javax.swing.JRadioButton();
        radioRecurring = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCardNumber = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblPin = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        checkAtm = new javax.swing.JCheckBox();
        checkMobile = new javax.swing.JCheckBox();
        checkInternet = new javax.swing.JCheckBox();
        checkEmail = new javax.swing.JCheckBox();
        checkBook = new javax.swing.JCheckBox();
        checkStatement = new javax.swing.JCheckBox();
        checkAgrement = new javax.swing.JCheckBox();

        buttonGroup1.add(radioSaving);
        buttonGroup1.add(radioCurrent);
        buttonGroup1.add(radioFixed);
        buttonGroup1.add(radioRecurring);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Account Details");
        jLabel1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jLabel1InputMethodTextChanged(evt);
            }
        });

        btnNext.setBackground(new java.awt.Color(51, 153, 0));
        btnNext.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setText("Finish");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(102, 0, 0));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblRandom.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblRandom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRandom.setText("..");
        lblRandom.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblRandomAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        lblRandom.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lblRandomInputMethodTextChanged(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel6.setText("Account Type");

        buttonGroup1.add(radioSaving);
        radioSaving.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radioSaving.setText("Saving Account");
        radioSaving.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSavingActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioCurrent);
        radioCurrent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radioCurrent.setText("Current Account");
        radioCurrent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCurrentActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioFixed);
        radioFixed.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radioFixed.setText("Fixed Deposit Acc");
        radioFixed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioFixedActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioRecurring);
        radioRecurring.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radioRecurring.setText("Recurring Deposite Acc");
        radioRecurring.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRecurringActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel7.setText("Card Number");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Your 16 digit card number");

        lblCardNumber.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        lblCardNumber.setText("XXXX-XXXX-XXXX-6589");
        lblCardNumber.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblCardNumberAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel9.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel9.setText("PIN");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Your 4 digit PIN number");

        lblPin.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        lblPin.setText("XXXX");
        lblPin.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblPinAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel11.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel11.setText("Service Requried");

        checkAtm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        checkAtm.setText("ATM Card");

        checkMobile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        checkMobile.setText("Mobile Banking");

        checkInternet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        checkInternet.setText("Internet Banking");

        checkEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        checkEmail.setText("Email & SMS Alert");

        checkBook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        checkBook.setText("Cheque Book");

        checkStatement.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        checkStatement.setText("E - Statement");

        checkAgrement.setForeground(new java.awt.Color(0, 51, 204));
        checkAgrement.setText("I hereby decleares that the above details are correct to the best of my knowledge");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(422, 422, 422)
                        .addComponent(lblRandom, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(radioSaving, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(radioFixed, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(radioCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(radioRecurring))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)
                                .addComponent(lblCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)
                                .addComponent(lblPin, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(checkAtm, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(checkMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(checkBook, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(checkAgrement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkStatement, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(checkInternet, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(checkEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)))
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblRandom)
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioSaving, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioFixed, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioRecurring, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkAtm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkMobile))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkInternet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkEmail)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBook)
                    .addComponent(checkStatement))
                .addGap(18, 27, Short.MAX_VALUE)
                .addComponent(checkAgrement)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jLabel1InputMethodTextChanged
        
    }//GEN-LAST:event_jLabel1InputMethodTextChanged

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        String card = lblCardNumber.getText();
        int pin =  Integer.parseInt(lblPin.getText());
        getServices();
        
        Account newAcc = new Account(nic,account, card, pin, services);
        try {
            boolean isAdded = AccountController.addAccount(newAcc);
            if(isAdded){
                JOptionPane.showMessageDialog(this, "Details Added to the system!");
            }else{
                JOptionPane.showMessageDialog(this, "Details did't add to the system!");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void lblRandomInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lblRandomInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lblRandomInputMethodTextChanged

    private void lblRandomAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblRandomAncestorAdded
        lblRandom.setText(random+"");
    }//GEN-LAST:event_lblRandomAncestorAdded

    private void radioFixedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioFixedActionPerformed
       account = "Fixed Deposit Acc";
    }//GEN-LAST:event_radioFixedActionPerformed

    private void radioRecurringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRecurringActionPerformed
        account = "Recurring Deposite Acc";
    }//GEN-LAST:event_radioRecurringActionPerformed

    private void radioSavingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSavingActionPerformed
        account = "Saving Account";
    }//GEN-LAST:event_radioSavingActionPerformed

    private void radioCurrentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCurrentActionPerformed
        account = "Current Account";
    }//GEN-LAST:event_radioCurrentActionPerformed

    private void lblCardNumberAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblCardNumberAncestorAdded
       lblCardNumber.setText(cardNumber);
    }//GEN-LAST:event_lblCardNumberAncestorAdded

    private void lblPinAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblPinAncestorAdded
        lblPin.setText(String.valueOf(pinNumber));
    }//GEN-LAST:event_lblPinAncestorAdded
    private void getServices(){
        if(checkAtm.isSelected()){
           services += "ATM Card, ";
        }
        if(checkMobile.isSelected()){
           services += "Mobile Banking, ";
        }
        if(checkBook.isSelected()){
           services += "Cheque Book, "; 
        }
        if(checkInternet.isSelected()){
            services += "Internet Banking, ";
        }
        if(checkEmail.isSelected()){
            services += "Email & SMS Alert, ";
        }
        if(checkEmail.isSelected()){
            services += "E - Statement ";
        }  
    }
    public static void main(String args[]) {
        Random r = new Random();
        long random = 5355 ;
        new SignUpThirdForm(random, "205458156178").setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnNext;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox checkAgrement;
    private javax.swing.JCheckBox checkAtm;
    private javax.swing.JCheckBox checkBook;
    private javax.swing.JCheckBox checkEmail;
    private javax.swing.JCheckBox checkInternet;
    private javax.swing.JCheckBox checkMobile;
    private javax.swing.JCheckBox checkStatement;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblCardNumber;
    private javax.swing.JLabel lblPin;
    private javax.swing.JLabel lblRandom;
    private javax.swing.JRadioButton radioCurrent;
    private javax.swing.JRadioButton radioFixed;
    private javax.swing.JRadioButton radioRecurring;
    private javax.swing.JRadioButton radioSaving;
    // End of variables declaration//GEN-END:variables
}
