/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bms.view;

import bms.DBConnection.DBConnection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.*;
/**
 *
 * @author acer
 */
public class SignUpSecForm extends javax.swing.JFrame {
    private long random;
    private String nic;
    private String religion;
    private String categ;
    private String income;
    private String edu;
    private String occu;
    private String ExAcc;
    /**
     * Creates new form SignUpForm
     */
    public SignUpSecForm(long random,String nic) {
        this.nic = nic;
        this.random = random;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        comboReligion = new javax.swing.JComboBox<>();
        comboCategory = new javax.swing.JComboBox<>();
        comboIncome = new javax.swing.JComboBox<>();
        comboEdu = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        comboSalary = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        radioYes = new javax.swing.JRadioButton();
        radioNo = new javax.swing.JRadioButton();
        lblRandom = new javax.swing.JLabel();

        buttonGroup1.add(radioYes);
        buttonGroup1.add(radioNo);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("New Account Application Form");
        jLabel1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jLabel1InputMethodTextChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Page 2 : Additional Details");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Religion : ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Category : ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Income : ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Education : ");

        btnNext.setBackground(new java.awt.Color(51, 153, 0));
        btnNext.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setText("Finish");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(102, 0, 0));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        comboReligion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        comboReligion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buddhist", "Catholic", "Muslim", "Christian", "Burger", "Other" }));
        comboReligion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboReligionActionPerformed(evt);
            }
        });

        comboCategory.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        comboCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General", "OBC", "SC", "ST", "Other", " " }));
        comboCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCategoryActionPerformed(evt);
            }
        });

        comboIncome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        comboIncome.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "less than 150,000  >", "more than 150,000 <", "more than 200,000 <", "more than 250,000 <", "less than 500,000 >", "more than 500,000 <" }));
        comboIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboIncomeActionPerformed(evt);
            }
        });

        comboEdu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        comboEdu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Non Gradguate", "Gradguate", "Post Gradguate", "Dectrate", "Other" }));
        comboEdu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEduActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Occupation : ");

        comboSalary.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        comboSalary.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Salaried", "Self-Employed", "Employee", "Student", "Retired", "Other", " " }));
        comboSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSalaryActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Exsisting Acc.:");

        radioYes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radioYes.setText("Yes");

        radioNo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radioNo.setText("No");

        lblRandom.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblRandom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRandom.setText("..");
        lblRandom.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblRandomAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        lblRandom.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lblRandomInputMethodTextChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblRandom, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(comboReligion, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(66, 66, 66)
                                .addComponent(comboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(comboIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(comboEdu, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(50, 50, 50)
                                .addComponent(comboSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(radioYes, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(radioNo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(240, 240, 240)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblRandom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboReligion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboEdu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioYes)
                    .addComponent(radioNo))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jLabel1InputMethodTextChanged
        
    }//GEN-LAST:event_jLabel1InputMethodTextChanged

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
       ExAcc = isExsisting();
        try {
            String SQL = "Insert into userAdditionalDetails values ('"+nic+"','"+religion+"','"+categ+"','"+income+"','"+edu+"','"+occu+"','"+ExAcc+"')";
            Statement stm = DBConnection.getInstance().getConnection().createStatement();
            int res = stm.executeUpdate(SQL);
            boolean isAdded = res>0;
            if(isAdded){
                JOptionPane.showMessageDialog(this, "Details Added to the system!");
            }else{
                JOptionPane.showMessageDialog(this, "Details did't add to the system!");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void lblRandomInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lblRandomInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lblRandomInputMethodTextChanged

    private void comboReligionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboReligionActionPerformed
        if("Buddhist".equals(comboReligion.getSelectedItem().toString())){
            religion = "Buddhist";
        }else if("Catholic".equals(comboReligion.getSelectedItem().toString())){
            religion = "Catholic";
        }else if("Muslim".equals(comboReligion.getSelectedItem().toString())){
            religion = "Muslim";
        }else if("Christian".equals(comboReligion.getSelectedItem().toString())){
            religion = "Christian";
        }else if("Burger".equals(comboReligion.getSelectedItem().toString())){
            religion = "Burger";
        }else if("Other".equals(comboReligion.getSelectedItem().toString())){
            religion = "Other";
        }
        System.out.println(religion);
        
    }//GEN-LAST:event_comboReligionActionPerformed

    private void comboCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCategoryActionPerformed
        if("General".equals(comboCategory.getSelectedItem().toString())){
            categ = "General";
        }else if("OBC".equals(comboCategory.getSelectedItem().toString())){
            categ = "OBC";
        }else if("SC".equals(comboCategory.getSelectedItem().toString())){
            categ = "SC";
        }else if("ST".equals(comboCategory.getSelectedItem().toString())){
            categ = "ST";
        }else if("Other".equals(comboCategory.getSelectedItem().toString())){
            categ = "Other";
        }

    }//GEN-LAST:event_comboCategoryActionPerformed

    private void comboIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboIncomeActionPerformed
         if("less than 150,000  >".equals(comboIncome.getSelectedItem().toString())){
            income = "less than 150,000  >";
        }else if("more than 150,000 <".equals(comboIncome.getSelectedItem().toString())){
            income = "more than 150,000 <";
        }else if("more than 200,000 <".equals(comboIncome.getSelectedItem().toString())){
            income = "more than 200,000 <";
        }else if("more than 250,000 <".equals(comboIncome.getSelectedItem().toString())){
            income = "more than 250,000 <";
        }else if("less than 500,000 >".equals(comboIncome.getSelectedItem().toString())){
            income = "less than 500,000 >";
        }else if("more than 500,000 <".equals(comboIncome.getSelectedItem().toString())){
            income = "more than 500,000 <";
        }
    }//GEN-LAST:event_comboIncomeActionPerformed

    private void comboEduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEduActionPerformed
        if("Non Gradguate".equals(comboEdu.getSelectedItem().toString())){
            edu = "Non Gradguate";
        }else if("Gradguate".equals(comboEdu.getSelectedItem().toString())){
            edu = "Gradguate";
        }else if("Post Gradguate".equals(comboEdu.getSelectedItem().toString())){
            edu = "Post Gradguate";
        }else if("Dectrate".equals(comboEdu.getSelectedItem().toString())){
            edu = "Dectrate";
        }else if("Other".equals(comboEdu.getSelectedItem().toString())){
            edu = "Other";
        }
    }//GEN-LAST:event_comboEduActionPerformed

    private void comboSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSalaryActionPerformed
         if("Salaried".equals(comboSalary.getSelectedItem().toString())){
            occu = "Salaried";
        }else if("Self-Employed".equals(comboSalary.getSelectedItem().toString())){
            occu = "Self-Employed";
        }else if("Employee".equals(comboSalary.getSelectedItem().toString())){
            occu = "Employee";
        }else if("Student".equals(comboSalary.getSelectedItem().toString())){
            occu = "Student";
        }else if("Retired".equals(comboSalary.getSelectedItem().toString())){
            occu = "Retired";
        }else if("Other".equals(comboSalary.getSelectedItem().toString())){
            occu = "Other";
        }

    }//GEN-LAST:event_comboSalaryActionPerformed

    private void lblRandomAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblRandomAncestorAdded
        lblRandom.setText(random+"");
    }//GEN-LAST:event_lblRandomAncestorAdded
        
    public String isExsisting(){
        if(radioYes.isSelected()){
            ExAcc = "yes";
        }else if(radioNo.isSelected()){
            ExAcc = "No";
        }else{
            JOptionPane.showMessageDialog(this, "Please select one option in Exsisting Account");
        }
        return ExAcc;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnNext;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboCategory;
    private javax.swing.JComboBox<String> comboEdu;
    private javax.swing.JComboBox<String> comboIncome;
    private javax.swing.JComboBox<String> comboReligion;
    private javax.swing.JComboBox<String> comboSalary;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblRandom;
    private javax.swing.JRadioButton radioNo;
    private javax.swing.JRadioButton radioYes;
    // End of variables declaration//GEN-END:variables
}
