/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bms.atm.view;

import bms.controller.AccountController;
import bms.controller.TransactionController;
import bms.model.Account;
import bms.model.Transactions;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class MiniState extends javax.swing.JFrame {
    private int pin;
    private ArrayList<Transactions>getAllAmount;
    /**
     * Creates new form MiniState
     */
    public MiniState(int pin) {
        this.pin = pin;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblCardNumber = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        amountTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bank of Sri Lanka");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 18, 351, 34));

        jLabel2.setText("Card Number : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 59, 91, 25));

        lblCardNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCardNumber.setText("XXXXXXXXXXXX");
        lblCardNumber.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblCardNumberAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(lblCardNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 58, -1, 25));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Your current account balance : ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 382, 202, -1));

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotal.setText("0.00");
        lblTotal.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblTotalAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 382, 130, -1));

        amountTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Date", "Type", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(amountTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 102, 325, 239));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("*** Thanks for using our banking service. ***");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 416, 340, 20));

        jLabel4.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("|||||||||||||||||||||||||||||||");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 350, 160, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void setDetails(int pin){
        try {
            ArrayList<Transactions>getDetails = TransactionController.getAllAmount(pin);
            DefaultTableModel dtm = (DefaultTableModel) amountTable.getModel();
            dtm.setRowCount(0);
            for(Transactions trans : getDetails){
                Object[] rowData={trans.getDate(),trans.getType(),trans.getAmount()};
                dtm.addRow(rowData);
            }
        } catch (ClassNotFoundException | SQLException | NullPointerException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
    private void lblCardNumberAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblCardNumberAncestorAdded
        try {
            Account getAcc = AccountController.getAccount(pin);
            lblCardNumber.setText(getAcc.getCardNumber().substring(0, 8)+"XXXX");
            setDetails(pin);
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_lblCardNumberAncestorAdded

    private void lblTotalAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblTotalAncestorAdded
        try {
            double total = getTotal();
            lblTotal.setText("Rs. "+total+"");
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
    }//GEN-LAST:event_lblTotalAncestorAdded
    private double getTotal() throws ClassNotFoundException, SQLException {
        getAllAmount = TransactionController.getAllAmount(pin);
        double totalAmount = 0;
        for (int i = 0; i < getAllAmount.size(); i++) {
            if("deposit".equals(getAllAmount.get(i).getType())){
                totalAmount += getAllAmount.get(i).getAmount();
            }else{
                totalAmount -= getAllAmount.get(i).getAmount();
            }
        }
        return totalAmount;
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable amountTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCardNumber;
    private javax.swing.JLabel lblTotal;
    // End of variables declaration//GEN-END:variables
}
