/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bms.atm.view;

import bms.controller.TransactionController;
import bms.model.Transactions;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class PinChange extends javax.swing.JFrame {
    private double value;
    private int pin;
    private ArrayList<Transactions> getAllAmount;
    private double balance;

    public PinChange(int pin) {
        this.pin = pin;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnWithdraw = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblPIN = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNewPIN = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNewPIN1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnExit = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("Before changing PIN number check user agreement");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 260, 30));

        btnWithdraw.setBackground(new java.awt.Color(51, 51, 255));
        btnWithdraw.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnWithdraw.setForeground(new java.awt.Color(255, 255, 255));
        btnWithdraw.setText("Change");
        btnWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawActionPerformed(evt);
            }
        });
        getContentPane().add(btnWithdraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 500, 100, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 50)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Bank of Sri Lanka");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 430, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Your Current PIN : ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, -1, 20));

        lblPIN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPIN.setForeground(new java.awt.Color(255, 255, 255));
        lblPIN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPIN.setText("0000");
        lblPIN.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblPINAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(lblPIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 70, -1));

        jButton1.setBackground(new java.awt.Color(0, 204, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 60, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Enter the NEW PIN number to account");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 230, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("RE-Enter new PIN :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 110, -1));
        getContentPane().add(txtNewPIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 110, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Enter new PIN :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 100, -1));
        getContentPane().add(txtNewPIN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 110, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Netbeans Projects\\Bank-Management-System\\Images\\dgsrsdfgr.jpg")); // NOI18N
        jLabel2.setText("Enter ");
        jLabel2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 672, 60, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        lblPIN.setText("");
        value = 0;      
    }//GEN-LAST:event_btnExitActionPerformed
    private double getTotal() throws ClassNotFoundException, SQLException {
        getAllAmount = TransactionController.getAllAmount(pin);
        double totalAmount = 0;
        for (int i = 0; i < getAllAmount.size(); i++) {
            totalAmount += getAllAmount.get(i).getAmount();
        }
        
        return totalAmount;

    }
    private void jLabel2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel2AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2AncestorAdded

    private void btnWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawActionPerformed
        if ("".equals(lblPIN.getText())) {
            JOptionPane.showMessageDialog(this, "Please Enter the amount you want to withdraw");
        }else{
            double amount = Double.parseDouble(lblPIN.getText());
            Date date = new Date();
            Transactions withdraw = new Transactions(pin, date, "withdraw", amount);
            try {
                double total = getTotal();
                System.out.println(total);
                if (amount > total) {
                    JOptionPane.showMessageDialog(this, "Your Total balance is "+total+"!");
                    lblPIN.setText("");
                    value = 0;
                } else {
                    boolean isAdded = TransactionController.depositAmount(withdraw);
                    if (isAdded) {
                        balance = total - amount;
                        int choice = JOptionPane.showConfirmDialog(null, "Rs. " + amount + " Withdrawal Successfull! Do you want to Withdraw More?", "Withdrawal Success", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
                        if (choice == JOptionPane.YES_OPTION) {
                            lblPIN.setText("");
                            value = 0;
                        } else {

                            dispose();
                            new TransactionForm(pin).setVisible(true);
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Your Withdrawal Unsuccessfull!");
                        lblPIN.setText("");
                    }
                }
            } catch (ClassNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnWithdrawActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        new TransactionForm(pin).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lblPINAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblPINAncestorAdded
        lblPIN.setText(pin+"");
    }//GEN-LAST:event_lblPINAncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnExit;
    private javax.swing.JButton btnWithdraw;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblPIN;
    private javax.swing.JTextField txtNewPIN;
    private javax.swing.JTextField txtNewPIN1;
    // End of variables declaration//GEN-END:variables
}
